### ISSUE TITLE
[BUG] Wild Red Grape Plants Drop White Grapes

### ISSUE THREAD

**Issue by DancingDragoness** [DragN0007/Fortuitous-Feasts#2]
Wild red grape plants drop white grapes instead of red.

**Comment by DragN0007** [comment]
Thanks for the report! I'll get it fixed asap and have it included in the next update :)

**Comment by DragN0007** [comment]
Fixed for 1.18 & 1.20!

**Comment by DancingDragoness** [comment]
Awesome!
